version: '3'

services:
  web:
    build: .
    container_name: talkfusion_web
    command: gunicorn Talkfusion.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080 --workers 4
    volumes:
      - .:/app
    expose:
      - "8080"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=Talkfusion.settings

  redis:
    image: redis:7
    container_name: talkfusion_redis
    ports:
      - "6378:6379"
  nginx:
    image: nginx:latest
    container_name: talkfusion_nginx
    ports:
      - "8000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/static
      - ./media:/media
    depends_on:
      - web
