version: '3'

services:
  # db:
  #   image: postgres:15
  #   container_name: talkfusion_db
  #   restart: always
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  web:
    build: .
    container_name: talkfusion_web
    command: gunicorn Talkfusion.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080 --workers 4
    volumes:
      - .:/app
    expose:
      - "8080"
    depends_on:
      - redis
      # - db
    environment:
      - DJANGO_SETTINGS_MODULE=Talkfusion.settings

  redis:
    image: redis:7
    container_name: talkfusion_redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A Talkfusion worker -l info --pool=solo
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
      - web
      # - db
    restart: always

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A Talkfusion beat -l info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
      - web
      # - db
    restart: always

  nginx:
    image: nginx:latest
    container_name: talkfusion_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

# volumes:
#   postgres_data:
